development:
  adapter: postgresql
  database: <%= Rails.application.secrets.db_name %> 
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>
  host: localhost
  timeout: 10000

test:
  adapter: postgresql
  database: <%= Rails.application.secrets.db_name %> 
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>
  host: localhost
  timeout: 10000

production:
  adapter: postgresql
  database: <%= Rails.application.secrets.db_name %> 
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>
  timeout: 10000